kosar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('modir.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('User/',include('users.urls'))
] 

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

modir/urls.py
from re import I
from django.urls import path
from . import views

app_name = 'modir'
urlpatterns = [
    path('', views.LoginView ,name='login'),
    path('home', views.home, name='home'),
    path('blank/',views.blank ),
    path('letter/new/',views.get_letter.as_view() , name='get_letter'),
    path('adminUsers/',views.adminUsers,name='adminUsers'),
    path('level/',views.level,name='level'),
    path('new_level/',views.new_level.as_view(),name='new_level'),
    path('postAppoinment/',views.postAppoinment.as_view(),name='PostAp'),
    path('Root/',views.Root.as_view(),name='Root'),
    path('dabirkhone/', views.dabirkhone, name='dabirkhone'),
    path('addDabirkhone/',views.AddDabirkhone.as_view(),name='addDabirkhone'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('add_user/<int:id>',views.AddUser.as_view() , name='user_add'),
    path('profile/<int:id>',views.Profile.as_view() , name='profile')
    
]

users/models.py
from operator import mod
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    personalcode = models.CharField(max_length=20, null=True, help_text='حداکثر ۲۰ کارکتر فقط اعداد ۰تا۹')
    mobileNumber = models.CharField(max_length=20, null=True)
    phoneNumber = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=100, null=True)

    
# add user models and form
# class UserProfile(models.Model):
#     user = models.OneToOneField(User , on_delete=models.CASCADE , default= User.username )
#     personalcode = models.IntegerField()
#     phone_number = models.CharField(max_length=20 ,null=True)


    # def __str__(self):
    #     return self.user.user_name
    

users/forms.py
from curses import meta
from dataclasses import field
from django import forms
from django.forms import ModelForm
from users.models import CustomUser
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
# from .models import UserProfile

# class Profile(UserChangeForm):
    
#     personalcode = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control'}))
    
#     user = forms.Select(attrs={'class':'form-control'})
    

#     class Meta:
#         model = UserProfile
#         fields = ('user','personalcode')

class AddUserForm(UserCreationForm):
    personalcode = forms.CharField(max_length = 20,widget=forms.TextInput(attrs={'class':'form-control'}))
    mobileNumber = forms.CharField(max_length = 20,widget=forms.TextInput(attrs={'class':'form-control'}))
    phoneNumber = forms.CharField(max_length = 20,widget=forms.TextInput(attrs={'class':'form-control'}))
    address = forms.CharField(max_length = 100,widget=forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length = 50,widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length = 50,widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(max_length = 50,widget=forms.TextInput(attrs={'class':'form-control'}))
    password1= forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control'}))
    password2= forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control'}))
    # groups = forms.ChoiceField()
    
    class Meta:
        model = CustomUser
        fields = ('personalcode','mobileNumber','phoneNumber','address','first_name','last_name', 'username', 'email', 'password1' ,'password2','groups')

        
        

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from users.models import CustomUser
from .forms import AddUserForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
# from .models import UserProfile
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm , UserChangeForm

# Create your views here hoow.

class Profile(generic.UpdateView):
    model = CustomUser
    fields = ['personalcode','mobileNumber','phoneNumber','address','first_name','last_name', 'username', 'email','groups']
    template_name = 'users/profile.html'
    success_url = reverse_lazy('modir:adminUsers')

    
    
    def get_object(self):
        return self.model.objects.get(id = self.kwargs.get('id', None))


class AddUser(generic.CreateView):
    form_class = AddUserForm
    template_name = 'users/add_user.html'
    success_url = reverse_lazy('modir:adminUsers')

    def get_object(self):
        return self.request.user

# def user_add(request):
    
#     # if this is a POST request we need to process the form data
#     if request.method == 'POST':
#         # create a form instance and populate it with data from the request:
#         form = AddUserForm(request.POST)
        
#         if form.is_valid():
#             form.save()

#             return HttpResponseRedirect(reverse('modir:adminUsers'))

#     # if a GET (or any other method) we'll create a blank form
#     else:
#         form = AddUserForm()

   
#     return render(request, 'users/add_user.html',{'form':form})

users/templates/users/add_user.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href={% static 'modir/css/custom.css'%}>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% block main %}


    <center><h3>ایجاد کاربر جدید </h3></center>
    <br>
    
            <form action="" method=POST>
                
                
                {% csrf_token %}
                
                
                <div class="form-row">

                    <div class="form-group col-lg-4">
                        <label for="">کد پرسنلی :</label>
                        {{form.personalcode}}
                    </div>
                    
                    <div class="form-group col-lg-4">
                        <label for="">نام :</label>
                        {{form.first_name}}
                    </div>

                    <div class="form-group col-lg-4">
                        <label for="">نام خانوادگی :</label>
                        {{form.last_name}}
                    </div>

                </div>
           


                <div class="form-row">

                    <div class="form-group col-lg-4">
                        <label for="">ایمیل  :  </label>
                        {{form.email}}
                    </div>

                    <div class="form-group col-lg-8">
                        <label for="">آدرس  :  </label>
                        {{form.address}}
                    </div>
                    
                </div>

                <div class="form-row">

                    <div class="form-group col-lg-4">
                        <label for="">نام کاربری  :  </label>
                        {{ form.username }}
                    </div>

                    <div class="form-group col-lg-4">
                        <label for="">رمز عبور  :  </label>
                        {{ form.password1 }}
                    </div>

                    <div class="form-group col-lg-4">
                        <label for="">تکرار رمز عبور  :  </label>
                        {{ form.password2 }}
                    </div>

                    
                </div>

                <div class="form-row">

                    <div class="form-group col-lg-4">
                        <label for="">شماره موبایل  :  </label>
                        {{ form.mobileNumber }}
                    </div>

                    <div class="form-group col-lg-4">
                        <label for="">تلفن  :  </label>
                        {{ form.phoneNumber }}
                    </div>

                    <div class="form-group col-lg-4">
                        <label for="">سطح دسترسی  :  </label>
                        {{form.groups}}
                    </div>
                </div>



                <input class="btn btn-primery" type="submit" value="ثبت کاربر جدید" >
            
        </form>

        <!-- <center><div class="alert alert-warning" role="alert">
            <h3>
            شما به این صفحه دسترسی ندارید لطفا برای برگشت 
            <a href={% url 'modir:home' %} class="alert-link">کلیک</a>
            کنید</h3>
          </div> </center>!-->
        




{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href={% static 'modir/css/custom.css'%}>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% block main %}


    <center><h3>ایجاد کاربر جدید </h3></center>
    <br>
    
            <form class="form-group" action="" method=POST>
                
                
                {% csrf_token %}
                
               
                <div class="form-row">
                    
                    <div class="form-group col-lg-12">
                        <label for=""> </label>
                        {{ form.as_p }}
                    </div>
                </div>
                



                <input class="btn btn-primery" type="submit" value="ثبت کاربر جدید" >
            
        </form>

        <!-- <center><div class="alert alert-warning" role="alert">
            <h3>
            شما به این صفحه دسترسی ندارید لطفا برای برگشت 
            <a href={% url 'modir:home' %} class="alert-link">کلیک</a>
            کنید</h3>
          </div> </center> !-->
        
          {% endblock%}

users/templates/users/user_added.html
thanks