kosar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('modir.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('User/',include('users.urls'))
] 

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

modir/urls.py
from re import I
from django.urls import path
from . import views

app_name = 'modir'
urlpatterns = [
    path('', views.LoginView ,name='login'),
    path('home', views.home, name='home'),
    path('blank/',views.blank ),
    path('letter/new/',views.get_letter.as_view() , name='get_letter'),
    path('adminUsers/',views.adminUsers,name='adminUsers'),
    path('level/',views.level,name='level'),
    path('new_level/',views.new_level.as_view(),name='new_level'),
    path('postAppoinment/',views.postAppoinment.as_view(),name='PostAp'),
    path('Root/',views.Root.as_view(),name='Root'),
    path('dabirkhone/', views.dabirkhone, name='dabirkhone'),
    path('addDabirkhone/',views.AddDabirkhone.as_view(),name='addDabirkhone'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('add_user/<int:id>',views.AddUser.as_view() , name='user_add'),
    path('profile/<int:id>',views.Profile.as_view() , name='profile')
    
]

modir/models.py
from operator import mod
from django.db import models
from users.models import CustomUser


class Root(models.Model):
    name = models.CharField(max_length=100)
    sign = models.BooleanField()

    def __str__(self):
        return self.name

class DabirKhone(models.Model):
    name = models.CharField(max_length=100)
    choiceDabirKhone = models.ForeignKey(CustomUser , on_delete=models.CASCADE)
    harfVarede = models.CharField(max_length=100)
    harfShomareDakheli = models.CharField(max_length=100)
    harfShomareSadere = models.CharField(max_length=100)
    shomareNameAghazin = models.CharField(max_length=100)

    def __str__(self):
        return self.name
        
        
class Level(models.Model):
    name = models.CharField(max_length = 51)
    nameplz = models.CharField(max_length = 51)
    sign = models.BooleanField()
    root = models.ForeignKey(Root , on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Letter(models.Model):
    subtitle = models.CharField(max_length=20,verbose_name='عنوان نامه')
    discription = models.CharField(max_length=100 , verbose_name='توضیحات')
    position = models.ForeignKey(Level , on_delete = models.CASCADE, related_name ='position')
    signatory = models.ForeignKey(Level , on_delete = models.CASCADE , related_name = 'signatory' )
    secretariat = models.ForeignKey(DabirKhone , on_delete = models.CASCADE, related_name ='secretariat')
    receivers = models.ForeignKey(Level , on_delete = models.CASCADE, related_name ='receivers')
    Transcript = models.ForeignKey(Level , on_delete = models.CASCADE, related_name ='Transcript')
    ready_text = models.CharField(max_length=50, choices=[('test','test')])
    size_letter = models.CharField(max_length=50, choices=[('A4','A4'),('A5','A5')])

    def __str__(self):
        return self.subtitle


class PostAppoinment(models.Model):
    post = models.ForeignKey(Root , on_delete=models.CASCADE , related_name= 'post')
    user = models.ForeignKey(CustomUser , on_delete=models.CASCADE , related_name= 'user')

    def __str__(self):
        return self.post 

modir/forms.py
from dataclasses import field
from django import forms
from django.forms import ModelForm
from .models import Letter , Level , PostAppoinment ,Root , DabirKhone


class DabirKhoneForm(ModelForm):
    class Meta:
        model = DabirKhone
        fields = ['name','choiceDabirKhone','harfVarede','harfShomareDakheli','harfShomareSadere','shomareNameAghazin']
        labels = {
            'name':'نام دبیرخانه',
            'choiceDabirKhone':'انتخاب کاربر دبیرخانه',
            'harfVarede':'حرف وارده',
            'harfShomareDakheli':'حرف شماره داخلی',
            'harfShomareSadere':'حرف شماره صادره',
            'shomareNameAghazin':'شماره نام اغازین',
        }


class RootForm(ModelForm):
    class Meta:
        model = Root
        fields = ['name','sign']
        labels = {
            'name':'نام ریشه ',
            'sign':'حق امضا',
        }

class PostAppoinmentForm(ModelForm):
    class Meta:
        model = PostAppoinment
        fields = ['post','user']
        labels = {
            'post':'انتخاب پست ',
            'user':'انتخاب کارمند',
        }

class NewLevelFrom(ModelForm):
    
    class Meta:
        model = Level
        fields = ['name','nameplz','sign','root']
        labels = {
            'name':'نام'
            ,'nameplz':'نام محترمانه'
            ,'sign':'حق امضا',
            'root':'ریشه'

        }

class LetterForm(ModelForm):
    class Meta:
        model = Letter
        fields = ['position','signatory','secretariat'
        ,'receivers','Transcript','subtitle','discription','ready_text','size_letter']
        labels = {
            'position':'ارسال کننده:'
            ,'signatory':'امضا کننده:',
            'secretariat':'انتخاب دبیرخانه:',
            'receivers':'گیرندگان:',
            'Transcript':'رونوشت:',
            'subtitle':'عنوان نامه:',
            'discription':'توضیحات:',
            'ready_text':'',
            'size_letter':'سایز برگه:',
            
        }

        # widgets = {
        #     'signatory':forms.Select(attrs={'class':'w3-input'}),
        #     'secretariat':forms.Select(attrs={'class':'w3-input'}),
        #     'position': forms.Select(attrs={'class':'w3-input'}),
        #     'Transcript':forms.CheckboxSelectMultiple(attrs={'class':'w3-input'}),
        #     'receivers': forms.CheckboxSelectMultiple(attrs={'class':'w3-input'}),
        #     'subtitle':forms.TextInput(attrs={'class':'form-control'}),
        #     'discription':forms.Textarea(attrs={'class':'form-control'}),
        #     'ready_text':forms.Select(attrs={'class':'w3-input'}),
        #     'size_letter':forms.RadioSelect(attrs={'class':'radio'}),
        # }
       

modir/views.py
import imp
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import LetterForm, NewLevelFrom , PostAppoinmentForm , RootForm , DabirKhoneForm
from django.contrib.auth.models import AbstractUser
from .models import Letter , DabirKhone, PostAppoinment , Level
from django.contrib.auth.backends import ModelBackend
from users.models import CustomUser
from django.contrib.auth import get_user_model
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
# from users.models import UserProfile

class AddDabirkhone(CreateView):
    form_class = DabirKhoneForm
    template_name = 'modir/add_dabirkhone.html'
    success_url = reverse_lazy('modir:dabirkhone')

    def get_object(self):
        return self.request.user


class Root(CreateView):
    form_class = RootForm
    template_name = 'modir/add_Root.html'
    success_url = reverse_lazy('modir:adminUsers')

    def get_object(self):
        return self.request.user


class postAppoinment(CreateView):
    form_class = PostAppoinmentForm
    template_name = 'modir/PostAp.html'
    success_url = reverse_lazy('modir:adminUsers')

    def get_object(self):
        return self.request.user

class new_level(CreateView):
    form_class = NewLevelFrom
    template_name = 'modir/new_level.html'
    success_url = reverse_lazy('modir:adminUsers')

    def get_object(self):
        return self.request.user

def level(request):
    level = Level.objects.all()
    return render(request , 'modir/level.html', {'Level':level})

def adminUsers(request):
    userfields = CustomUser.objects.all()
    # profile = UserProfile.objects.all()
    
    return render(request,'modir/admin-users.html',{'field':userfields})

class get_letter(CreateView):
    form_class = LetterForm
    template_name = 'modir/newletter.html'
    success_url = reverse_lazy('modir:home')

    def get_object(self):
        return self.request.user

    

def home(request):
    letter = Letter.objects.all()

    return render(request,'modir/index.html', {'letter':letter})

def blank(request):
    return render(request,'modir/blank.html')

def LoginView(request):
    return HttpResponseRedirect(reverse('login'))

def dabirkhone(request):
    dabir = DabirKhone.objects.all()
    post = PostAppoinment.objects.all()
    return render(request,'modir/dabirkhone.html', {'dabir': dabir, 'Post':post })

modir/templates/modir/PostAp.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href={% static 'modir/css/custom.css'%}>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% block main %}

<!-- {% if perms.modir.add_letter %} -->
    <center><h3>ایجاد پست </h3></center>
    <br>
    
            <form action="" method=POST>
                
                
                {% csrf_token %}
                {{form}}
                <input type="submit" value="ایجاد پست" >
            <!-- <div class="w3-card-4">
                <div class="form-row">
                    <div class="form-group col-lg-4">
                        <label for="">ارسال کننده  :  </label>
                        {{form.position}}
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="">امضا کننده  :  </label>
                        {{form.signatory}}
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="">انتخاب دبیرخانه  :  </label>
                        {{form.secretariat}}
                    </div>
                </div>
            </div> -->

            
        </form>
<!-- {% else %} -->
        <!-- <center><div class="alert alert-warning" role="alert">
            <h3>
            شما به این صفحه دسترسی ندارید لطفا برای برگشت 
            <a href={% url 'modir:home' %} class="alert-link">کلیک</a>
            کنید</h3>
          </div> </center>
        

{% endif %} -->


{% endblock %}

modir/templates/modir/add_Root.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href={% static 'modir/css/custom.css'%}>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% block main %}


    <center><h3>ایجاد پست </h3></center>
    <br>
    
            <form action="" method=POST>
                
                
                {% csrf_token %}
                {{form}}
                <input type="submit" value="ایجاد پست" >
        </form>



{% endblock %}

modir/templates/modir/admin-users.html
{% extends "base.html" %}
{% load static %}

{% block main %}


<aside class="lg-side">
    <div class="inbox-head">
        <div class="mail-option">
            <div>
                <p>  مدیریت کاربران</p>

                <a class="btn btn-info" style="float: left;">اجرای عملیات</a>
                <select class="selectTag" name="action">
                    <option value="1">         تغییر به مدیر</option>
                    <option value="2">          تغییر به دبیرخانه </option>
                    <option value="3">       تغییر به کاربر عادی </option>
                    <option value="4">    حذف   </option>
                </select>
                <a href={% url 'users:user_add' user.id %} class="btn btn-info" style="float: right;margin-left:15px; ">   کاربر جدید  </a>
                
            </div>
        </div>
    </div>


<form action="" method="post">
    <div class="inbox-body">

        <table class="table   table-hover">
            <thead>
                <tr>
                  <th>کد پرسنلی</th>
                  <th>نام</th>
                  <th>نام خانوادگی</th>
                  <th>موبایل</th>
                  <th>ایمیل</th>
                  <th>نام کاربری</th>
                  <th>نوع کاربری</th>
                  <th>انتخاب</th>
                </tr>
              </thead>
              <tbody>
                {% for fields in field %}
                
                <tr>
                  <td>{{fields.personalcode}}</td>
                  <td>{{fields.first_name}}</td>
                  <td>{{fields.last_name}}</td>
                  <td>{{fields.mobileNumber}}</td>
                  <td>{{fields.email}}</td>
                  <td>{{fields.username}}</td>
                  <td>{{fields.groups}}</td>
                  <td><a class="mini tooltips" href={% url 'users:profile' fields.id %} data-placement="top" data-original-title="ویرایش"><i class="icon-edit"></i></a></td>
                </tr>
                {% endfor %}
</form>
        </aside>

{% endblock%}

modir/templates/modir/dabirkhone.html
{% extends "base.html" %}
{% load static %}

{% block main %}



        <style>
            .selectTag {
                float: left;
                margin-left: 10px;
                font-family: yekan;
                font-size: 10 . pt;
                padding: 1px;
            }
        </style>
        <aside class="lg-side">
            <div class="inbox-head">
                <div class="mail-option">
                    <div>
                        <p class="title">
                            مدیریت دبیرخانه ها
                        </p>
                        <a class="btn btn-info" style="float: left; " onclick="submitFormMulti();">
                            اجرای عملیات
                        </a>

                        <select class="selectTag" name="action">
                            <option value="1"> حذف  </option>
                        </select>
                        <a href={% url 'modir:addDabirkhone' %} class="btn btn-info" style="float: right;margin-left:15px; ">
                            دبیرخانه جدید        </a>
                        <script>
                            function submitFormMulti() {
                                var actionSelected = $('.selectTag option:selected').val();
                                var action = '';
                                if (actionSelected == 1) {
                                    action = 'deleteDabir';
                                }
                                var form = $('form');
                                form.attr('action', action);
                                form.submit();
                            }
                        </script>
                    </div>
                </div>
            </div>

            <form action="" method="post">
                <div class="inbox-body">
                    
                    <table class="table   table-hover">
                        <tbody>
                        <tr class="row_header">
                            <td class="view-message">نام دبیرخانه</td>
                            <td class="view-message">نام کاربر </td>
                            <td class="view-message">حرف شماره نامه وارده</td>
                            <td class="view-message">حرف شماره نامه داخلی</td>
                            <td class="view-message">حرف شماره نامه صادره</td>
                            <td class="view-message">شماره نامه آغازین</td>
                            <td class="view-message">پست انتصاب داده شده</td>
                            <td class="view-message ">انتخاب </td>
                        </tr>
                        {% for Dabir in dabir %}
                            {% for post in Post %}
                            <tr>
                                <td>{{Dabir.name}}</td>
                                <td>{{Dabir.choiceDabirKhone}}</td>
                                <td>{{Dabir.harfVarede}}</td>
                                <td>{{Dabir.harfShomareDakheli}}</td>
                                <td>{{Dabir.harfShomareSadere}}</td>
                                <td>{{Dabir.shomareNameAghazin}}</td>
                                <td>{{post.post}}</td>
                                
                                <td>
                                    <input type="checkbox" name="id[]" value="1">
                                    <a href="addDabirkhone/1"><i class="icon-edit"></i></a>
                                </td>
                                {% endfor %}
                                {% endfor %}
                            
                                                    </tbody>

                    </table>
                    
                </div> 
            </form>
        </aside>

  

{% endblock %}

modir/templates/modir/index.html
{% extends "base.html" %}




{% block main %}

            
            
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        
                        <section>
                            <div class="panel panel-default" style="background: rgb(131, 136, 190); ">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-lg-3 col-sm-6"><img src="..." alt="..." class="img-circle"></div>
                                        <div class="col-lg-6 col-sm-6"><h5 style="color: white;">مدیر اتوماسیون</h4></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4 col-sm-6"></div>
                                        <div class="col-lg-8 col-sm-6">
                                            <select name="" id="">
                                                <option value="">مدیر</option>
                                                <option value="">مدیریت</option>
                                                <option value="">بارگزاری</option>
                                                <option value="">مدیریتی</option>
                                                <option value="">قبل</option>
                                                <option value="">برنامه</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                              </div>
                        </section>

                    </div>      
                    

                    <div class="col-lg-9 col-sm-6">
                        
                        <section>
                            <div class="panel panel-default" style="background: rgb(174, 177, 179);">
                                <div class="panel-body">
                                    <div class="mail-option">
                                        <h6 style="color: white;">جستجو در :</h6>
                                        <div style="display: inline-flex;">
                                                <select style="width: 100px; font-size: 12px;" class="form-control" name="" id="">
                                                        <option value="">شماره نامه</option>
                                                        <option value="">عنوان نامه </option>
                                                        <option value="">فرستنده نامه</option>
                                                        <option value=""></option>
                                                        <option value=""></option>
                                                </select>
                                                <input style="width: 300px;" class="form-control" placeholder="جستجو نامه..." type="text" name="" id="">
                                                <button class="icon-search btn"></button>
                                        </div>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </section>
                            
                    </div>
    
                </div>
            
                <div style="padding: 0 12px;" class="row">
                        <div class="col-lg-3 col-sm-6">

                            <section>
                                <div class="panel panel-default" style="background: rgb(178, 215, 219); ">
                                    <div class="panel-body">
                                        <div><a href={% url 'modir:get_letter' %}><button class="btn btn-custom">نامه جدید</button></a></div>
                                         <div class="btn-group-vertical"> 
                                                <button class="btn btn-custom1">نامه های دریافتی</button>
                                                <button class="btn btn-custom1">نامه های ارسالی</button>
                                                <button class="btn btn-custom1">پیش نویس    <span class="badge">42</span></button>
                                                <button class="btn btn-custom1">بایگانی</button>
                                                
                                          </div> 
                                    </div>
                                </div>
                            </section>

                        </div>

                        <div class="col-lg-9 col-sm-6">

                            <section>
                                
                                    <div class="panel panel-default" style="background: rgb(253, 254, 255); ">
                                        <div class="panel-body">
                                            <table style="width: 700px;" class="table">
                                                <tr>
                                                    
                                                    <th>فرستنده</th>
                                                    <th>عنوان</th>
                                                    <th>توضیحات</th>
                                                    <th>پیوست</th>
                                                    <th>تاریخ</th>
                                                    <th>شماره نامه</th>
                                                  </tr>
                                                <!-- {% for Letter in letter %}
                                                  <tr>
                                                    <th>{{Letter.position}}</th>
                                                    <th>{{Letter.subtitle}}</th>
                                                    <th>{{Letter.discription}}</th>
                                                    
                                                  </tr>
                                                  {% endfor %} -->

                                                  {% for post in Post %}
                                                  <tr>
                                                    <th>{{post.post}}</th>
                                                    <th>{{post.user}}</th>
                                                    
                                                    
                                                  </tr>
                                                  {% endfor %}
                                              </table>
                                        </div>
                                    </div>
                                
                            </section>

                        </div>

                </div>
            
                <!-- page end-->
            </section>
        
{% endblock %}
    

modir/templates/modir/level.html
{% extends "base.html" %}




{% block main %}
      

       
            

                <style>
                    .selectTag {
                        float: left;
                        margin-left: 10px;
                        font-family: yekan;
                        font-size: 10 . pt;
                        padding: 1px;
                    }
                </style>
                <aside class="lg-side">
                    <div class="inbox-head">
                        <div class="mail-option">
                            <div>
                <p class="title">
                        مدیریت سلسله مراتب
                </p>
                <a class="btn btn-info" style="float: left; " >
                    اجرای عملیات
                </a>

                <select class="selectTag" name="action">
                    <option value="1"> حذف  </option>
                </select>
                <a href={% url 'modir:new_level'%} class="btn btn-info" style="float: right;margin-left:15px; ">
                    پست جدید        </a>
                <script>
                    function submitFormMulti() {
                        var actionSelected = $('.selectTag option:selected').val();
                        var action = '';
                        if (actionSelected == 1) {
                            action = 'deleteLevel';
                        }
                        var form = $('form');
                        form.attr('action', action);
                        form.submit();
                    }
                </script>
                            </div>
                        </div>
                    </div>

                    <table class="table   table-hover">
                        <tbody>
                        <tr class="row_header">
                            <td class="view-message">سمت</td>
                            <td class="view-message">نام محترمانه</td>
                            <td class="view-message">حق امضا</td>
                            <td class="view-message">ریشه</td>
                            
                        </tr>
                        {% for level in Level %}
                            
                            <tr>
                                <td>{{level.name}}</td>
                                <td>{{level.nameplz}}</td>
                                {% if level.sign %}
                                <td>دارد</td>
                                {% else %}
                                <td>ندارد</td>
                                {% endif %}
                                <td>{{level.root}}</td>
                                
                                <td>
                                    <input type="checkbox" name="id[]" value="1">
                                    <a href="addDabirkhone/1"><i class="icon-edit"></i></a>
                                </td>
                                
                                {% endfor %}
                            
                                                    </tbody>

                    </table>
                </aside>
           
        

{% endblock %}

modir/templates/modir/new_level.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href={% static 'modir/css/custom.css'%}>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% block main %}

<!-- {% if perms.modir.add_letter %} -->
    <center><h3>ایجاد پست </h3></center>
    <br>
    
            <form action="" method=POST>
                
                
                {% csrf_token %}
                {{form}}
                <input type="submit" value="ایجاد پست" >
            <!-- <div class="w3-card-4">
                <div class="form-row">
                    <div class="form-group col-lg-4">
                        <label for="">ارسال کننده  :  </label>
                        {{form.position}}
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="">امضا کننده  :  </label>
                        {{form.signatory}}
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="">انتخاب دبیرخانه  :  </label>
                        {{form.secretariat}}
                    </div>
                </div>
            </div> -->

            
        </form>
<!-- {% else %} -->
        <!-- <center><div class="alert alert-warning" role="alert">
            <h3>
            شما به این صفحه دسترسی ندارید لطفا برای برگشت 
            <a href={% url 'modir:home' %} class="alert-link">کلیک</a>
            کنید</h3>
          </div> </center>
        

{% endif %} -->


{% endblock %}

modir/templates/modir/newletter.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href={% static 'modir/css/custom.css'%}>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% block main %}

{% if perms.modir.add_letter %}
    <center><h3>نامه جدید</h3></center>
    <br>
    
            <form action="" method=POST>
                
                
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primery" type="submit" value="ایجاد نامه" >
            <!-- <div class="w3-card-4">
                <div class="form-row">
                    <div class="form-group col-lg-4">
                        <label for="">ارسال کننده  :  </label>
                        {{form.position}}
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="">امضا کننده  :  </label>
                        {{form.signatory}}
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="">انتخاب دبیرخانه  :  </label>
                        {{form.secretariat}}
                    </div>
                </div>
            </div>


                <div class="form-row">
                    <div class="form-group col-lg-6">
                        <label for="">گیرندگان  :  </label>
                        {{form.receivers}}
                    </div>
                    <div class="form-group col-lg-6">
                        <label for="">رونوشت  :  </label>
                        {{form.Transcript}}
                    </div>
                    
                </div>


                <div class="form-row">
                    <div class="form-group col-lg-5">                       
                        {{form.subtitle}}
                    </div>
                    <div class="form-group col-lg-3">
                        {{form.discription}}
                    </div>
                    <div class="form-group col-lg-2">
                        {{form.ready_text}}
                    </div>
                    <div class="form-group col-lg-2">
                        {{form.size_letter}}
                    </div>
                    
                </div> -->
            
        </form>
{% else %}
        <center><div class="alert alert-warning" role="alert">
            <h3>
            شما به این صفحه دسترسی ندارید لطفا برای برگشت 
            <a href={% url 'modir:home' %} class="alert-link">کلیک</a>
            کنید</h3>
          </div> </center>
          

{% endif %}


{% endblock %}